### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by realwill** [zimenglan-sysu-512/Focal-Loss#6]
the error is：

layer {
  name: "conv3_4/3/concat"
  type: "Concat"
  bottom: "conv3_4/3/pre"
  bottom: "conv3_4/3/neg"
  top: "conv3_4/3/preAct"
}
layer {
  name: "conv3_4/3/scale"
  
I0911 19:56:15.271533 56548 layer_factory.hpp:77] Creating layer input-data
I0911 19:56:15.272256 56548 net.cpp:100] Creating Layer input-data
I0911 19:56:15.272281 56548 net.cpp:408] input-data -> data
I0911 19:56:15.272305 56548 net.cpp:408] input-data -> im_info
I0911 19:56:15.272316 56548 net.cpp:408] input-data -> gt_boxes
Segmentation fault

**Comment by zimenglan-sysu-512** [comment]
It seems it's your network problem.

**Comment by realwill** [comment]
@zimenglan-sysu-512 it's numpy's version

**Comment by hp-93** [comment]
@realwill  I meet the same problem and How can I solve it？

**Comment by hp-93** [comment]
I get that error has been solved after I first run make clean and  then make -j32
