### ISSUE TITLE
about the alpha parameter

### ISSUE THREAD

**Issue by JayYangSS** [zimenglan-sysu-512/Focal-Loss#8]
It seems that you multiply the alpha(default is 0.25) to all the samples when calculating the loss. But the alpha parameter mentioned in the paper controls the weight of different class. So I think the weighting factor alpha should be different when calculate the different class samples.

**Comment by zimenglan-sysu-512** [comment]
hi @JayYangSS,
you are right, here i just share the same alpha for all categories using sofrmax loss instead of binary classifier.

**Comment by brisker** [comment]
@zimenglan-sysu-512 
so  in the problem of classification of more than 2 classes, is there any difference if I set alpha to 1, compared to 0.25?

**Comment by knsong** [comment]
@brisker  In this case, `alpha` will act just as a loss weight.
